anchor_version = "0.18.2"

[workspace]
members = [
    ".",
]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
serum_dex = "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX"
